### ISSUE TITLE
Inspect  the test for GML 3.2.2

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-gml32#44]
Check if the test is covering 3.2.1 version, per conversation at the TC June 25th 2019.

**Comment by dstenger** [comment]
It must be checked if GML 3.2.2 is covered by test suite.

**Comment by dstenger** [comment]
Possible actions:
- Create issue to updated documentation, if needed.
- Create issue to implement GML 3.2.2 tests, if needed.

**Comment by dstenger** [comment]
We are looking for example/test files to verify and document the current status.

**Comment by ghobona** [comment]
The ETS does not include the GML 3.2.2 schema, so it currently supports 3.2.1

https://github.com/opengeospatial/ets-gml32/blob/master/src/main/resources/org/opengis/cite/iso19136/xsd/opengis/gml/3.2.1/gml-3.2.1.xsd

![Screenshot 2020-05-26 at 10 01 25](https://user-images.githubusercontent.com/18121038/82881800-17881280-9f38-11ea-8f6d-dcedad8a121d.png)

**Comment by heidivanparys** [comment]
But shouldn't the test support GML 3.2.2 instead of GML 3.2.1, as 3.2.2 is the version in effect now? That was the original issue as I remember from the meeting in June 2019.

http://schemas.opengis.net/gml/3.2.1/gml.xsd

![image](https://user-images.githubusercontent.com/11427611/82899755-c9850600-9f5b-11ea-86a7-7cf1ceab67bf.png)

http://schemas.opengis.net/gml/ReadMe.txt

![image](https://user-images.githubusercontent.com/11427611/82899773-d0137d80-9f5b-11ea-9930-3313567ac214.png)

So a test could be to have a GML document containing a feature with no gml:id (as it has been made option), and that GML document should pass the test instead of failing with a violation that gml:id has to be present.

**Comment by ghobona** [comment]
@heidivanparys You are correct that the ETS should support GML 3.2.2. The original ticket was about inspecting whether the ETS supports version 3.2.2 or 3.2.1, hence after determining that the ETS supports version 3.2.1 the ticket was closed.

We are now looking into when we will be able to extend the ETS to support GML 3.2.2.

We will add GML 3.2.2 to the [Roadmap](https://docs.google.com/spreadsheets/d/1Kfi8kha80PAwzMaW0iK2qPtJNU5dGgLafROOQdTAdGw/#gid=1412922823), with implementation likely to start March 2021. However, if a volunteer offers to help out, support for GML 3.2.2 could be implemented sooner.
